// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCategoryApp.Data;

namespace ProductCategoryApp.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190524182757_AddedModels")]
    partial class AddedModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductCategoryApp.Models.CategoryModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ProductCategoryApp.Models.ColorModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("ID");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("ProductCategoryApp.Models.ProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoryID");

                    b.Property<Guid?>("ColorID");

                    b.Property<decimal>("CurrentValue");

                    b.Property<string>("Description");

                    b.Property<decimal>("Length_X");

                    b.Property<decimal>("Length_Y");

                    b.Property<decimal>("Length_Z");

                    b.Property<string>("Name");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<decimal>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ColorID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductCategoryApp.Models.ProductModel", b =>
                {
                    b.HasOne("ProductCategoryApp.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("ProductCategoryApp.Models.ColorModel", "Color")
                        .WithMany()
                        .HasForeignKey("ColorID");
                });
#pragma warning restore 612, 618
        }
    }
}
