// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCategoryApp.Data;

namespace ProductCategoryApp.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductCategoryApp.Models.CategoryModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CollectionID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("CollectionID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ProductCategoryApp.Models.CollectionModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("ProductCategoryApp.Models.ProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoryID");

                    b.Property<string>("Color");

                    b.Property<decimal>("CurrentValue");

                    b.Property<string>("Description");

                    b.Property<decimal>("Length_X");

                    b.Property<decimal>("Length_Y");

                    b.Property<decimal>("Length_Z");

                    b.Property<string>("Name");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<decimal>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductCategoryApp.Models.CategoryModel", b =>
                {
                    b.HasOne("ProductCategoryApp.Models.CollectionModel", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionID");
                });

            modelBuilder.Entity("ProductCategoryApp.Models.ProductModel", b =>
                {
                    b.HasOne("ProductCategoryApp.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
